project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Chronologies
    right:
      - href: publications/index.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: blog/index.qmd
        
      
format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]

