project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Chronologies
    logo: Logo.png
    right:
      - href: research/MapTest_Static.qmd
        text: Research
      - href: guidance/index.qmd
        text: Guidance
      - href: about2.qmd
        text: About us
    
  

     
format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]

